### PR TITLE
Added basic support for snapshots

### PR DESCRIPTION
**Pull request by trevor-vaughan**

### CODE REVIEW

**Comment by lnemsick-simp** [comment]
Please add a the `snapshot` suite to GitLab

**Comment by trevor-vaughan** [comment]
:hourglass_flowing_sand: https://gitlab.com/simp/rubygem-simp-beaker-helpers/pipelines/72746136

**Comment by lnemsick-simp** [comment]
When I ran the snapshot acceptance test locally,  one of the servers didn't restore properly from snapshot.  `vagrant status` said the machine was up and running, but `vagrant ssh -- -vvv` showed no connectivity.

**Comment by trevor-vaughan** [comment]
@lnemsick-simp Probably a local system issue: https://gitlab.com/simp/rubygem-simp-beaker-helpers/-/jobs/258486760

**Comment by trevor-vaughan** [comment]
Hmm...I saw this previously and was trying to reproduce it without much success. From GitLab:

```
Stderr: VBoxManage: error: Snapshot 'server-el6_simp_beaker_base' of the machine 'defaultyml_server-el6_1563984519867_48485' cannot be deleted, because it is the current snapshot and has one child snapshot
```

**Comment by trevor-vaughan** [comment]
Looks like this may depend on the version of VirtualBox and/or vagrant that are in use. Trying to find some way to reproduce.

**Comment by trevor-vaughan** [comment]
Found a reproducer, trying to figure out how to handle it

**Comment by trevor-vaughan** [comment]
:hourglass_flowing_sand: https://gitlab.com/simp/rubygem-simp-beaker-helpers/pipelines/72800960

**Comment by lnemsick-simp** [comment]
:heavy_check_mark: https://gitlab.com/simp/rubygem-simp-beaker-helpers/pipelines/73214801

**Pull request merged**
