### PR TITLE
Fix default module path for copy_fixtures_to

### PR DESCRIPTION
**Pull request by alexharv074**
See discussion in the [Beaker mailing list](https://groups.google.com/forum/#!topic/puppet-beaker/IxMlNUIRLLA).

### CODE REVIEW

**Comment by alexharv074** [comment]
```
commit 99e5ea502c6e7e74c5bced1adc5a2de67047162e
Author: Alex Harvey <>
Date:   Wed Mar 16 19:30:10 2016 +1100

    Allow suts to be a String
    
    If a string is passed in to copy_fixture_modules_to have it interpreted
    as a SUT, rather than an Array of SUTs.

commit 71ccea806995b9d1be68a8782f5f3416ad7b21b7
Author: Alex Harvey <>
Date:   Wed Mar 16 19:21:52 2016 +1100

    Correct defaults for copy_fixture_modules_to()
    
    As a result of BKR-723, copy_module_to() defaults to
    host['distmoduledir'] and this has not been updated with a valid default
    for Puppet 4.
    
    Since we do not expect BKR-723 to be fixed quickly, we have
    copy_fixture_modules_to provide its own default, namely the default module path in Puppet 4,
    /opt/puppetlabs/code/modules.
```

**Comment by alexharv074** [comment]
Looking into why the tests failed.

**Comment by alexharv074** [comment]
The only test that's failing for me is:

```
server 12:08:24$ puppet facts find xxx
  /usr/bin/nmcli: symbol lookup error: /lib64/libgudev-1.0.so.0: undefined symbol: g_type_class_adjust_private_offset
  {"name":"xxx","values":{"sshrsakey":"AAAAB3NzaC1yc2EAAAADAQABAAABAQDLMo35gwbuqQvRq1gy6L8vddeyMNBYr5WPVcftMKSJR1jmwzxcZ+h0AEb3KPfoMHkqe9Xy+3oN981qe5ZCE780HO884AaXzXry9zdWQjGysrI+zHQbqbpOkYAGsVbJiQ7VnH7
lMVZo2jCbABj4OdsbeCOeP3oDXTNCTaWWdQChzqvYgNBvb0mg/na1l0naQ1nsJYD85O8ZRQ9U/JOADMaOjummfOb2z7MgskZ9abm5eFCCQl+wUUNXKqQx+uyVM4lyyoTHpW3M2IV0P9wxhWJF6eovwyREGuMgJCs6kbHCFty7HtAYbzziabgQav8pMe68aBqjshbpU6ll/
+aXWhD1","sshfp_rsa":"SSHFP 1 1 f25e9ad2faddbe75263cfee4fa97dc965bc1d581\nSSHFP 1 2 0173e386031a134e4cbfb7f6971788761a5aa3d9e39dafcf163f003de2537199","sshecdsakey":"AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIb
mlzdHAyNTYAAABBBBcSUcHQOfBDZElr6PBmxc/4ZDaIhsugXM7OE2SQj35iOMCN/I3XfINMo8SvBIQ6CsBqPnzgbKRBs7e1FPFnsT4=","sshfp_ecdsa":"SSHFP 3 1 91edfdf5e7e098f4392606865c017dabc26804bb\nSSHFP 3 2 f00c65a1884bfec52db1
1de89254f0bfd46baf9e759546654c94371a05ee0dba","architecture":"x86_64","system_uptime":{"seconds":39,"hours":0,"days":0,"uptime":"0:00 hours"},"augeasversion":"1.4.0","timezone":"UTC","kernel":"Linux","b
lockdevice_sda_size":21474836480,"blockdevice_sda_vendor":"ATA","blockdevice_sda_model":"VBOX HARDDISK","blockdevices":"sda","domain":"gateway","virtual":"virtualbox","is_virtual":true,"hardwaremodel":"
x86_64","operatingsystem":"CentOS","os":{"name":"CentOS","family":"RedHat","release":{"major":"7","minor":"0","full":"7.0.1406"}},"facterversion":"2.4.6","filesystems":"xfs","fqdn":"server.gateway","gid
":"root","hardwareisa":"x86_64","hostname":"server","id":"root","interfaces":"enp0s3,enp0s8,lo","ipaddress_enp0s3":"10.0.2.15","macaddress_enp0s3":"08:00:27:39:18:3c","netmask_enp0s3":"255.255.255.0","m
tu_enp0s3":1500,"ipaddress_enp0s8":"10.255.219.228","macaddress_enp0s8":"08:00:27:2c:d7:b2","netmask_enp0s8":"255.255.0.0","mtu_enp0s8":1500,"ipaddress_lo":"127.0.0.1","netmask_lo":"255.0.0.0","mtu_lo":
65536,"ipaddress":"10.0.2.15","kernelmajversion":"3.10","kernelrelease":"3.10.0-327.10.1.el7.x86_64","kernelversion":"3.10.0","rubyplatform":"x86_64-linux","rubysitedir":"/usr/local/share/ruby/site_ruby
/","macaddress":"08:00:27:39:18:3c","boardmanufacturer":"Oracle Corporation","boardproductname":"VirtualBox","boardserialnumber":"0","bios_vendor":"innotek GmbH","bios_version":"VirtualBox","bios_releas
e_date":"12/01/2006","manufacturer":"innotek GmbH","productname":"VirtualBox","serialnumber":"0","uuid":"BC80A76E-8D8B-4145-B336-825A66599562","type":"Other","memorysize":"237.36 MB","memoryfree":"90.29
 MB","swapsize":"1.03 GB","swapfree":"1.03 GB","swapsize_mb":"1056.00","swapfree_mb":"1055.04","memorysize_mb":"237.36","memoryfree_mb":"90.29","netmask":"255.255.255.0","network_enp0s3":"10.0.2.0","net
work_enp0s8":"10.255.0.0","network_lo":"127.0.0.0","operatingsystemmajrelease":"7","rubyversion":"2.0.0","operatingsystemrelease":"7.0.1406","osfamily":"RedHat","partitions":{"sda1":{"uuid":"39ce4ad1-4e
9d-49a4-bce0-8a30b459490a","size":"1024000","mount":"/boot","filesystem":"xfs"},"sda2":{"size":"40916992","filesystem":"LVM2_member"}},"path":"PATH:/usr/bin:/opt/puppet-git-repos/hiera/bin:/usr/local/sb
in:/usr/local/bin:/usr/sbin:/usr/bin:/sbin","selinux":false,"physicalprocessorcount":1,"processors":{"models":["Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz"],"count":1,"physicalcount":1},"processor0":"Int
el(R) Core(TM) i7-4850HQ CPU @ 2.30GHz","processorcount":1,"ps":"ps -ef","puppetversion":"3.8.6","uniqueid":"007f0100","uptime":"0:00 hours","uptime_days":0,"uptime_hours":0,"uptime_seconds":39,"clientc
ert":"server.gateway","clientversion":"3.8.6","clientnoop":false},"timestamp":"2016-03-17 01:08:24 +0000","expiration":"2016-03-17T01:38:24.774234529+00:00"}

server executed in 1.18 seconds
    should return value of root_home (FAILED - 1)
```

And while I don't know what's causing it, I can't see how it could be related to my change.

**Comment by alexharv074** [comment]
Ok, I've tested the code and it does what it's supposed to do.  I'm OK for you to merge this.

**Comment by alexharv074** [comment]
@trevor-vaughan

**Comment by alexharv074** [comment]
Wait, no.

I see this in the logs:

```
Using scp to transfer /Users/alexharvey/git/elk/spec/fixtures/modules/role to /opt/puppetlabs/code/modules/role
localhost $ scp /Users/alexharvey/git/elk/spec/fixtures/modules/role centos-72-x64:/opt/puppetlabs/code/modules {:ignore => [".bundle", ".git", ".idea", ".vagrant", ".vendor", "vendor", "acceptance", "b
undle", "spec", "tests", "log", ".", ".."]}
going to ignore (?-mix:((\/|\A)\.bundle(\/|\z))|((\/|\A)\.git(\/|\z))|((\/|\A)\.idea(\/|\z))|((\/|\A)\.vagrant(\/|\z))|((\/|\A)\.vendor(\/|\z))|((\/|\A)vendor(\/|\z))|((\/|\A)acceptance(\/|\z))|((\/|\A)
bundle(\/|\z))|((\/|\A)spec(\/|\z))|((\/|\A)tests(\/|\z))|((\/|\A)log(\/|\z))|((\/|\A)\.(\/|\z))|((\/|\A)\.\.(\/|\z)))

centos-72-x64 13:42:35$ echo /opt/puppetlabs/code/modules
  /opt/puppetlabs/code/modules
```

But afterwards it's empty.

**Comment by alexharv074** [comment]
Ok, I have discovered another bug in the same method that is blocking me.  I'll add another bugfix to the PR.

**Comment by alexharv074** [comment]
Ok, it's doing what it's supposed to do now, and I'm happy for this to be merged, noting that I couldn't explain the acceptance test failure [above](https://github.com/simp/rubygem-simp-beaker-helpers/pull/15#issuecomment-197648482).

**Comment by alexharv074** [comment]
@trevor-vaughan  Would you like to cancel this, or shall I fix it up in some way?  As I mentioned in the mailing list, after I got my head around what was required, it became clear to me that I should write my own helper methods in [my spec_helper_acceptance.rb](https://github.com/alexharv074/elk/blob/master/spec/spec_helper_acceptance.rb).  I'm more than happy to edit this PR if you'd still like to merge some of it though.

**Comment by op-ct** [comment]
@alexharv074, I've merged both `copy_fixtures_to()` fixes in as f8aa14a and patched up the tests and code (to autodetect each SUT's `modulepath`) in d8834d7.  The resulting gem has been published to  [rubygems.org](https://rubygems.org/gems/simp-beaker-helpers) as  version `1.4.0`.

Thanks for the great patches!

**Pull request closed without merging**
